<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>NAS on PyYoshiのログ置き場</title>
    <link>http://github.pyyoshi.com/blog/tags/NAS/</link>
    <description>Recent content in NAS on PyYoshiのログ置き場</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>ja</language>
    <lastBuildDate>Tue, 07 Aug 2012 06:59:00 +0900</lastBuildDate>
    
	<atom:link href="http://github.pyyoshi.com/blog/tags/NAS/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>NASのHDDを復旧準備</title>
      <link>http://github.pyyoshi.com/blog/2012/08/NAS%E3%81%AEHDD%E3%82%92%E5%BE%A9%E6%97%A7%E6%BA%96%E5%82%99/</link>
      <pubDate>Tue, 07 Aug 2012 06:59:00 +0900</pubDate>
      
      <guid>http://github.pyyoshi.com/blog/2012/08/NAS%E3%81%AEHDD%E3%82%92%E5%BE%A9%E6%97%A7%E6%BA%96%E5%82%99/</guid>
      <description>ここ最近調子が悪いNAS。 そしておいておいたファイルがデバイスエラーで読み込めなくなってしまった。
ファイルシステムがXFSという事もあってLinux機につないで作業を行った。
まずマウントできるか試した。
$sudo mkdir /mnt/nas
$sudo mount -t xfs /dev/sdc1 /mnt/nas
SuperBlockがどうのこうのというよくわからないエラーが出た。
調べてみるとxfsprogsでなんとかなるかもしれないらしい。
$sudo apt-get install xfsprogs
$sudo reboot
バックアップの作成
$sudo mkdir /mnt/tmp
$sudo dd if=/dev/sdc1 of=/mnt/tmp/broken.img ibs=512 obs=1024k conv=noerror,sync
$sudo xfs_check /dev/sdc1
 found candidate secondary superblock&amp;hellip;
verified secondary superblock&amp;hellip;
writing modified primary superblock
sb root inode value 18446744073709551615 (NULLFSINO) inconsistent with calculated value 128
resetting superblock root inode pointer to 128
sb realtime bitmap inode 18446744073709551615 (NULLFSINO) inconsistent with calculated value 129</description>
    </item>
    
  </channel>
</rss>